In [1]:
import numpy as np

In [43]:
oneD = np.array([1,2,3])
twoD = np.array([ [1,2,3,4,5,6], [7,8,9,10,11,12], [13,14,15,16,17,18] ])
threeD = np.array([ [ [1,2,3], [1,2,3]], [ [1,2,3], [1,2,3] ] ], dtype = np.int8)

In [44]:
print(oneD)
oneD.shape

[1 2 3]


(3,)

In [45]:
print(twoD)
twoD.shape

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]]


(3, 6)

In [63]:
print(threeD)
threeD.shape

[[[1 2 3]
  [1 2 3]]

 [[1 2 3]
  [1 2 3]]]


(2, 2, 3)

In [64]:
np.__version__

'1.21.5'

In [67]:
help(np.void)

Help on class void in module numpy:

class void(flexible)
 |  Either an opaque sequence of bytes, or a structure.
 |  
 |  >>> np.void(b'abcd')
 |  void(b'\x61\x62\x63\x64')
 |  
 |  Structured `void` scalars can only be constructed via extraction from :ref:`structured_arrays`:
 |  
 |  >>> arr = np.array((1, 2), dtype=[('x', np.int8), ('y', np.int8)])
 |  >>> arr[()]
 |  (1, 2)  # looks like a tuple, but is `np.void`
 |  
 |  :Character code: ``'V'``
 |  
 |  Method resolution order:
 |      void
 |      flexible
 |      generic
 |      builtins.object
 |  
 |  Methods defined here:
 |  
 |  __delitem__(self, key, /)
 |      Delete self[key].
 |  
 |  __eq__(self, value, /)
 |      Return self==value.
 |  
 |  __ge__(self, value, /)
 |      Return self>=value.
 |  
 |  __getitem__(self, key, /)
 |      Return self[key].
 |  
 |  __gt__(self, value, /)
 |      Return self>value.
 |  
 |  __hash__(self, /)
 |      Return hash(self).
 |  
 |  __le__(self, value, /)
 |      Return self<=v